version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "visor-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10l264fefmmgn"
s3_prefix = "visor-stack"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "AppName=\"visor-documentos-api\""
image_repositories = []
